"""THE CORE (meeting 2026-07-02): optimize semantic embeddings under the causal constraints derived from a
GIVEN graph. The optimization variables are the EMBEDDINGS themselves — latent u_j and unlabeled-observed
s_i. No encoder is trained (labeled embeddings a_i come from a frozen encoder and are fixed), so there is no
semantic-drift failure mode.

Objective (see README): visible labels must be generated by the graph; unlabeled nodes equal their
generation; latent children stay consistent with their latent parents; marginally independent pairs
decorrelate; unit-norm regularization keeps embeddings decode-stable.
"""
import numpy as np


def resolve_device(torch, device="auto"):
    """Use CUDA by default when PyTorch can see a GPU."""
    if device is None or str(device).lower() == "auto":
        return "cuda" if torch.cuda.is_available() else "cpu"
    return device


def optimize_embeddings(g, W, labeled_emb, d, steps=1500, lr=5e-2, lam_zero=0.3, lam_norm=0.1,
                        seed=0, device="auto", verbose=False):
    """g: graph.Graph; W: dict edge->signed weight (given support, data-estimated);
    labeled_emb: dict observed_name -> np.array[d] (frozen, VISIBLE labels only).
    Returns dict node_name -> np.array[d] for ALL nodes (labeled ones pass through unchanged)."""
    import torch
    torch.manual_seed(seed)
    device = resolve_device(torch, device)
    labeled = set(labeled_emb)
    free = [n for n in g.nodes if n not in labeled]                  # latents + unlabeled observed
    if not free:
        return dict(labeled_emb)
    # init: each free node starts at the weighted mean of its labeled neighbours (parents/children), else 0
    init = {}
    for n in free:
        nb = [p for p in g.parents(n) if p in labeled] + [c for c in g.children(n) if c in labeled]
        if nb:
            v = np.mean([labeled_emb[x] for x in nb], 0)
            init[n] = v / (np.linalg.norm(v) + 1e-9)
        else:
            init[n] = np.zeros(d)
    E = {n: torch.nn.Parameter(torch.tensor(init[n], dtype=torch.float32, device=device)) for n in free}
    A = {n: torch.tensor(v, dtype=torch.float32, device=device) for n, v in labeled_emb.items()}

    def emb(n):
        return A[n] if n in A else E[n]

    def gen(n):
        ps = g.parents(n)
        if not ps:
            return None
        tot = None
        for p in ps:
            w = float(W.get((p, n), 0.0))
            t = w * emb(p)
            tot = t if tot is None else tot + t
        return tot

    zero_pairs = [(a, b) for a, b in g.independent_pairs()]
    opt = torch.optim.Adam(list(E.values()), lr=lr)
    for step in range(steps):
        opt.zero_grad()
        loss = 0.0
        for n in g.nodes:
            gn = gen(n)
            if gn is None:
                continue
            if n in A:                                               # visible label: graph must generate it
                loss = loss + ((gn - A[n]) ** 2).sum()
            else:                                                    # free node: equals its generation
                loss = loss + ((E[n] - gn) ** 2).sum()
        if zero_pairs and lam_zero > 0:
            zp = 0.0
            for a, b in zero_pairs:
                ea, eb = emb(a), emb(b)
                na = ea / (ea.norm() + 1e-9)
                nb = eb / (eb.norm() + 1e-9)
                zp = zp + (na @ nb) ** 2
            loss = loss + lam_zero * zp / len(zero_pairs)
        if lam_norm > 0:
            nr = 0.0
            for n in free:
                nr = nr + (E[n].norm() - 1.0) ** 2
            loss = loss + lam_norm * nr / len(free)
        loss.backward()
        opt.step()
        if verbose and (step % 300 == 0 or step == steps - 1):
            print(f"  [optimize step {step}/{steps} loss={float(loss):.4f}]", flush=True)
    out = {n: v.detach().cpu().numpy().astype(np.float64) for n, v in E.items()}
    out.update({n: np.asarray(v, np.float64) for n, v in labeled_emb.items()})
    return out
